### ISSUE TITLE
Idea: catch ipython InteractiveShellEmbed

### ISSUE THREAD

**Issue by coagulant** [JBKahn/flake8-debugger#2]
```
from IPython.frontend.terminal.embed import InteractiveShellEmbed
InteractiveShellEmbed()()
```

**Comment by JBKahn** [comment]
Never heard of it. I'll check it out this week, but I don't see why not to include it

**Comment by JBKahn** [comment]
totally didn't get a chance to. will tomorrow. :)

**Comment by JBKahn** [comment]
I didn't abandon you. I just realized how hard coded all this logic was. I'm going to rewrite it so that adding new checkers is easier and the code is more generic.

**Comment by JBKahn** [comment]
added in 1.4.0

**Comment by coagulant** [comment]
Thnx!
