### ISSUE TITLE
3.1.1 flags any builtins import

### ISSUE THREAD

**Issue by The-Compiler** [JBKahn/flake8-debugger#20]
After upgrading to 3.1.1, this file:

```python3
import builtins
```

gets flagged as:

```
x.py:1:1: T100 import for builtins found
```

due to the changes in #16 - cc @rafikdraoui

(Also, this change was made in a patchlevel release and not mentioned in the changelog at all, which made it hard to track down...)

**Comment by JBKahn** [comment]
My bad, I forgot to include it in the changelog which is why it was a patch and not a minor version.

I'll take a look

**Comment by JBKahn** [comment]
3.2.0 was shipped with a fix
