### ISSUE TITLE
Cannot install package from source

### ISSUE THREAD

**Issue by seppeljordan** [JBKahn/flake8-debugger#22]
Hi, since you moved to `poetry` your package cannot be installed from source anymore.

See https://github.com/pypa/pip/issues/5739 for reference.

**Comment by JBKahn** [comment]
Is the alternative moving back? I don't see a resolution. Is there an alternative to those building from source?

**Comment by seppeljordan** [comment]
Unfortunately the only resolution of this that I know of would be for `poetry` to vendor their build requirements.

**Comment by JBKahn** [comment]
Ok, I'll switch back for now :disappointed: 

I see they are debating the solution to this inside poetry as well, Python tooling....

I'll put something out this week.

**Comment by JBKahn** [comment]
https://github.com/sdispater/poetry/issues/760

For reference so I can revisit this later

**Comment by seppeljordan** [comment]
Thanks for the heads up.

For people coming here from the internets:
`flake8-debugger<3.1` should work if you install from source.

**Comment by JBKahn** [comment]
fixed in 3.2.1

**Comment by seppeljordan** [comment]
Thank you very much :)

**Comment by JBKahn** [comment]
Thanks for reporting it!
